import "@/styles/globals.css";

import { Toaster } from "@/components/ui/toaster";
import { TRPCClientProvider } from "@/trpc/client";
import { Inter } from "next/font/google";

const inter = Inter({
	subsets: ["latin"],
});

export const metadata = {
	title: "Create T3 App",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<TRPCClientProvider>
					{children}
					<Toaster />
				</TRPCClientProvider>
			</body>
		</html>
	);
}
